-- AlterTable
ALTER TABLE `notificationconfig` ADD COLUMN `firstDelaySeconds` INTEGER NULL,
    MODIFY `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- CreateTable
CREATE TABLE `visitorpopupconfig` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `shop` VARCHAR(191) NOT NULL,
    `enabled` BOOLEAN NOT NULL DEFAULT false,
    `notiType` VARCHAR(191) NULL,
    `layout` VARCHAR(191) NULL,
    `size` INTEGER NULL,
    `transparent` INTEGER NULL,
    `template` VARCHAR(191) NULL,
    `imageAppearance` VARCHAR(191) NULL,
    `bgColor` VARCHAR(191) NULL,
    `bgAlt` VARCHAR(191) NULL,
    `textColor` VARCHAR(191) NULL,
    `timestampColor` VARCHAR(191) NULL,
    `priceTagBg` VARCHAR(191) NULL,
    `priceTagAlt` VARCHAR(191) NULL,
    `priceColor` VARCHAR(191) NULL,
    `starColor` VARCHAR(191) NULL,
    `textSizeContent` INTEGER NULL,
    `textSizeCompareAt` INTEGER NULL,
    `textSizePrice` INTEGER NULL,
    `message` LONGTEXT NULL,
    `timestamp` VARCHAR(191) NULL,
    `avgTime` VARCHAR(191) NULL,
    `avgUnit` VARCHAR(191) NULL,
    `productNameMode` VARCHAR(191) NULL,
    `productNameLimit` INTEGER NULL,
    `directProductPage` BOOLEAN NULL,
    `showProductImage` BOOLEAN NULL,
    `showPriceTag` BOOLEAN NULL,
    `showRating` BOOLEAN NULL,
    `ratingSource` VARCHAR(191) NULL,
    `customerInfo` VARCHAR(191) NULL,
    `showHome` BOOLEAN NULL,
    `showProduct` BOOLEAN NULL,
    `productScope` VARCHAR(191) NULL,
    `showCollectionList` BOOLEAN NULL,
    `showCollection` BOOLEAN NULL,
    `collectionScope` VARCHAR(191) NULL,
    `showCart` BOOLEAN NULL,
    `position` VARCHAR(191) NULL,
    `showClose` BOOLEAN NULL,
    `hideOnMobile` BOOLEAN NULL,
    `delay` INTEGER NULL,
    `duration` INTEGER NULL,
    `interval` INTEGER NULL,
    `intervalUnit` VARCHAR(191) NULL,
    `randomize` BOOLEAN NULL,
    `selectedProductsJson` LONGTEXT NULL,
    `selectedCollectionsJson` LONGTEXT NULL,

    INDEX `VisitorPopupConfig_shop_idx`(`shop`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `lowstockpopupconfig` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `shop` VARCHAR(191) NOT NULL,
    `enabled` BOOLEAN NOT NULL DEFAULT false,
    `layout` VARCHAR(191) NULL,
    `size` INTEGER NULL,
    `transparent` INTEGER NULL,
    `template` VARCHAR(191) NULL,
    `imageAppearance` VARCHAR(191) NULL,
    `bgColor` VARCHAR(191) NULL,
    `bgAlt` VARCHAR(191) NULL,
    `textColor` VARCHAR(191) NULL,
    `numberColor` VARCHAR(191) NULL,
    `priceTagBg` VARCHAR(191) NULL,
    `priceTagAlt` VARCHAR(191) NULL,
    `priceColor` VARCHAR(191) NULL,
    `starColor` VARCHAR(191) NULL,
    `textSizeContent` INTEGER NULL,
    `textSizeCompareAt` INTEGER NULL,
    `textSizePrice` INTEGER NULL,
    `message` LONGTEXT NULL,
    `productNameMode` VARCHAR(191) NULL,
    `productNameLimit` INTEGER NULL,
    `dataSource` VARCHAR(191) NULL,
    `stockUnder` INTEGER NULL,
    `hideOutOfStock` BOOLEAN NULL,
    `directProductPage` BOOLEAN NULL,
    `showProductImage` BOOLEAN NULL,
    `showPriceTag` BOOLEAN NULL,
    `showRating` BOOLEAN NULL,
    `showHome` BOOLEAN NULL,
    `showProduct` BOOLEAN NULL,
    `productScope` VARCHAR(191) NULL,
    `showCollectionList` BOOLEAN NULL,
    `showCollection` BOOLEAN NULL,
    `collectionScope` VARCHAR(191) NULL,
    `showCart` BOOLEAN NULL,
    `position` VARCHAR(191) NULL,
    `showClose` BOOLEAN NULL,
    `hideOnMobile` BOOLEAN NULL,
    `delay` INTEGER NULL,
    `duration` INTEGER NULL,
    `interval` INTEGER NULL,
    `intervalUnit` VARCHAR(191) NULL,
    `randomize` BOOLEAN NULL,
    `selectedProductsJson` LONGTEXT NULL,
    `selectedCollectionsJson` LONGTEXT NULL,

    INDEX `LowStockPopupConfig_shop_idx`(`shop`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `addtocartpopupconfig` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `shop` VARCHAR(191) NOT NULL,
    `enabled` BOOLEAN NOT NULL DEFAULT false,
    `layout` VARCHAR(191) NULL,
    `size` INTEGER NULL,
    `transparent` INTEGER NULL,
    `template` VARCHAR(191) NULL,
    `bgColor` VARCHAR(191) NULL,
    `bgAlt` VARCHAR(191) NULL,
    `textColor` VARCHAR(191) NULL,
    `timestampColor` VARCHAR(191) NULL,
    `priceTagBg` VARCHAR(191) NULL,
    `priceTagAlt` VARCHAR(191) NULL,
    `priceColor` VARCHAR(191) NULL,
    `starColor` VARCHAR(191) NULL,
    `textSizeContent` INTEGER NULL,
    `textSizeCompareAt` INTEGER NULL,
    `textSizePrice` INTEGER NULL,
    `message` LONGTEXT NULL,
    `timestamp` VARCHAR(191) NULL,
    `productNameMode` VARCHAR(191) NULL,
    `productNameLimit` INTEGER NULL,
    `dataSource` VARCHAR(191) NULL,
    `stockUnder` INTEGER NULL,
    `hideOutOfStock` BOOLEAN NULL,
    `directProductPage` BOOLEAN NULL,
    `showProductImage` BOOLEAN NULL,
    `showPriceTag` BOOLEAN NULL,
    `showRating` BOOLEAN NULL,
    `showHome` BOOLEAN NULL,
    `showProduct` BOOLEAN NULL,
    `productScope` VARCHAR(191) NULL,
    `showCollectionList` BOOLEAN NULL,
    `showCollection` BOOLEAN NULL,
    `collectionScope` VARCHAR(191) NULL,
    `showCart` BOOLEAN NULL,
    `position` VARCHAR(191) NULL,
    `showClose` BOOLEAN NULL,
    `hideOnMobile` BOOLEAN NULL,
    `delay` INTEGER NULL,
    `duration` INTEGER NULL,
    `interval` INTEGER NULL,
    `intervalUnit` VARCHAR(191) NULL,
    `randomize` BOOLEAN NULL,
    `selectedProductsJson` LONGTEXT NULL,
    `selectedCollectionsJson` LONGTEXT NULL,

    INDEX `AddToCartPopupConfig_shop_idx`(`shop`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `reviewpopupconfig` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `shop` VARCHAR(191) NOT NULL,
    `enabled` BOOLEAN NOT NULL DEFAULT false,
    `reviewType` VARCHAR(191) NULL,
    `template` VARCHAR(191) NULL,
    `imageAppearance` VARCHAR(191) NULL,
    `bgColor` VARCHAR(191) NULL,
    `bgAlt` VARCHAR(191) NULL,
    `textColor` VARCHAR(191) NULL,
    `timestampColor` VARCHAR(191) NULL,
    `priceTagBg` VARCHAR(191) NULL,
    `priceTagAlt` VARCHAR(191) NULL,
    `priceColor` VARCHAR(191) NULL,
    `starColor` VARCHAR(191) NULL,
    `textSizeContent` INTEGER NULL,
    `textSizeCompareAt` INTEGER NULL,
    `textSizePrice` INTEGER NULL,
    `message` LONGTEXT NULL,
    `timestamp` VARCHAR(191) NULL,
    `productNameMode` VARCHAR(191) NULL,
    `productNameLimit` INTEGER NULL,
    `dataSource` VARCHAR(191) NULL,
    `directProductPage` BOOLEAN NULL,
    `showProductImage` BOOLEAN NULL,
    `showPriceTag` BOOLEAN NULL,
    `showRating` BOOLEAN NULL,
    `showHome` BOOLEAN NULL,
    `showProduct` BOOLEAN NULL,
    `productScope` VARCHAR(191) NULL,
    `showCollectionList` BOOLEAN NULL,
    `showCollection` BOOLEAN NULL,
    `collectionScope` VARCHAR(191) NULL,
    `showCart` BOOLEAN NULL,
    `position` VARCHAR(191) NULL,
    `showClose` BOOLEAN NULL,
    `hideOnMobile` BOOLEAN NULL,
    `delay` INTEGER NULL,
    `duration` INTEGER NULL,
    `interval` INTEGER NULL,
    `intervalUnit` VARCHAR(191) NULL,
    `randomize` BOOLEAN NULL,
    `selectedProductsJson` LONGTEXT NULL,
    `selectedCollectionsJson` LONGTEXT NULL,

    INDEX `ReviewPopupConfig_shop_idx`(`shop`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `recentpopupconfig` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `shop` VARCHAR(191) NOT NULL,
    `enabled` BOOLEAN NOT NULL DEFAULT false,
    `showType` VARCHAR(191) NULL,
    `messageText` LONGTEXT NULL,
    `fontFamily` VARCHAR(191) NULL,
    `position` VARCHAR(191) NULL,
    `animation` VARCHAR(191) NULL,
    `mobileSize` VARCHAR(191) NULL,
    `mobilePositionJson` LONGTEXT NULL,
    `template` VARCHAR(191) NULL,
    `layout` VARCHAR(191) NULL,
    `imageAppearance` VARCHAR(191) NULL,
    `bgColor` VARCHAR(191) NULL,
    `bgAlt` VARCHAR(191) NULL,
    `textColor` VARCHAR(191) NULL,
    `numberColor` VARCHAR(191) NULL,
    `priceTagBg` VARCHAR(191) NULL,
    `priceTagAlt` VARCHAR(191) NULL,
    `priceColor` VARCHAR(191) NULL,
    `starColor` VARCHAR(191) NULL,
    `rounded` INTEGER NULL,
    `firstDelaySeconds` INTEGER NULL,
    `durationSeconds` INTEGER NULL,
    `alternateSeconds` INTEGER NULL,
    `intervalUnit` VARCHAR(191) NULL,
    `fontWeight` INTEGER NULL,
    `productNameMode` VARCHAR(191) NULL,
    `productNameLimit` INTEGER NULL,
    `orderDays` INTEGER NULL,
    `createOrderTime` VARCHAR(32) NULL,
    `messageTitlesJson` LONGTEXT NULL,
    `locationsJson` LONGTEXT NULL,
    `namesJson` LONGTEXT NULL,
    `selectedProductsJson` LONGTEXT NULL,

    INDEX `RecentPopupConfig_shop_idx`(`shop`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `flashpopupconfig` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `shop` VARCHAR(191) NOT NULL,
    `enabled` BOOLEAN NOT NULL DEFAULT false,
    `showType` VARCHAR(191) NULL,
    `messageTitle` VARCHAR(191) NULL,
    `name` VARCHAR(191) NULL,
    `messageText` LONGTEXT NULL,
    `fontFamily` VARCHAR(191) NULL,
    `fontWeight` INTEGER NULL,
    `layout` VARCHAR(191) NULL,
    `imageAppearance` VARCHAR(191) NULL,
    `template` VARCHAR(191) NULL,
    `position` VARCHAR(191) NULL,
    `animation` VARCHAR(191) NULL,
    `mobileSize` VARCHAR(191) NULL,
    `mobilePositionJson` LONGTEXT NULL,
    `bgColor` VARCHAR(191) NULL,
    `bgAlt` VARCHAR(191) NULL,
    `textColor` VARCHAR(191) NULL,
    `numberColor` VARCHAR(191) NULL,
    `priceTagBg` VARCHAR(191) NULL,
    `priceTagAlt` VARCHAR(191) NULL,
    `priceColor` VARCHAR(191) NULL,
    `starColor` VARCHAR(191) NULL,
    `rounded` INTEGER NULL,
    `firstDelaySeconds` INTEGER NULL,
    `durationSeconds` INTEGER NULL,
    `alternateSeconds` INTEGER NULL,
    `intervalUnit` VARCHAR(191) NULL,
    `iconKey` VARCHAR(191) NULL,
    `iconSvg` LONGTEXT NULL,
    `messageTitlesJson` LONGTEXT NULL,
    `locationsJson` LONGTEXT NULL,
    `namesJson` LONGTEXT NULL,
    `selectedProductsJson` LONGTEXT NULL,

    INDEX `FlashPopupConfig_shop_idx`(`shop`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
